import react from "@vitejs/plugin-react";
import { defineConfig, loadEnv } from "vite";

/**
 * No backend URL is baked into the bundle. `/api/auth/*` is proxied in dev so
 * the session cookie is first-party; in production Caddy does the same on the
 * site origin. `/.well-known` is served from `public/` locally (generated by
 * scripts/write-well-known.ts). Theme CSS variables are emitted by Tailwind
 * from `@aulora/tokens` (see tailwind.config.ts).
 */
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "");
  const authProxyTarget = env.AULORA_AUTH_PROXY_TARGET ?? "http://127.0.0.1:3211";

  return {
    plugins: [react()],
    server: {
      proxy: {
        "/api/auth": { target: authProxyTarget, changeOrigin: true },
      },
    },
    build: {
      outDir: "dist",
      sourcemap: false,
    },
  };
});
