import react from "@vitejs/plugin-react";
import { defineConfig, loadEnv } from "vite";

/**
 * No backend URL is baked into the bundle. `/api/auth/*` is proxied in dev so
 * the session cookie is first-party; in production Caddy does the same on the
 * site origin. `/.well-known` is served from `public/` locally (generated by
 * scripts/write-well-known.ts). Theme CSS variables are emitted by Tailwind
 * from `@aulora/tokens` (see tailwind.config.ts).
 */
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "");
  const authProxyTarget = env.AULORA_AUTH_PROXY_TARGET ?? "http://127.0.0.1:3211";

  return {
    plugins: [react()],
    server: {
      host: "127.0.0.1",
      port: 5173,
      strictPort: true,
      allowedHosts: env.AULORA_DEV_ALLOWED_HOST ? [env.AULORA_DEV_ALLOWED_HOST] : [],
      proxy: {
        "/api/auth": {
          target: authProxyTarget,
          changeOrigin: true,
          // Better Auth validates the request `Origin` against the server's
          // trusted origins. In local dev the app is served from Vite (5173)
          // while the server trusts its own site origin, so rewrite the header
          // to the server's origin for the auth surface only.
          configure: (proxy) => {
            proxy.on("proxyReq", (proxyReq) => {
              proxyReq.setHeader("Origin", authProxyTarget);
            });
          },
        },
        "/api": {
          target: authProxyTarget,
          changeOrigin: true,
          ws: true,
        },
      },
    },
    build: {
      outDir: "dist",
      sourcemap: false,
    },
  };
});
