# syntax=docker/dockerfile:1.7
#
# Builds the Aulora web SPA and serves it with nginx.
#   - multi-stage: Bun build -> nginx (alpine)
#   - history fallback for the TanStack Router SPA
#   - /.well-known/ served from the `web-well-known` volume (see nginx/default.conf)
#   - /api/auth/ proxied to the Convex HTTP-actions origin for first-party cookies
#
# Build context is the repo root; see ../../.dockerignore.

FROM oven/bun:1.4.0 AS build
WORKDIR /app

# Public values baked into the build-time dev well-known document. The runtime
# document is generated by `setup` and mounted over this path, so these only
# matter for a plain `vite build`.
ARG INSTANCE_NAME=Aulora
ARG SITE_URL=http://localhost:8080
ARG CONVEX_URL=http://localhost:3210
ENV INSTANCE_NAME=$INSTANCE_NAME
ENV SITE_URL=$SITE_URL
ENV CONVEX_URL=$CONVEX_URL

# Manifests first for a cacheable install.
COPY package.json bun.lock turbo.json tsconfig.json biome.json ./
COPY apps/web/package.json apps/web/
COPY packages ./packages
COPY apps/web ./apps/web
RUN bun install --frozen-lockfile

RUN bun run --cwd apps/web build

FROM nginx:1.27-alpine AS runtime
COPY infra/docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html
EXPOSE 80
